# Generated by Django 6.0.1 on 2026-02-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Address_line1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Address_line2',
            new_name='address_line2',
        ),
    ]
